from models import User
users = [
    User(name="Alice Johnson", username="alicej"),
    User(name="Bob Smith", username="bobsmith"),
    User(name="Charlie Brown", username="charlieb"),
    User(name="Diana Prince", username="dianap"),
    User(name="Evan Wright", username="evanw"),
    User(name="Fiona Lee", username="fionalee"),
    User(name="George Taylor", username="georget"),
    User(name="Hannah Davis", username="hannahd"),
    User(name="Ian Miller", username="ianm"),
    User(name="Julia Roberts", username="juliar"),
    User(name="Kevin Chang", username="kevinc"),
    User(name="Lily Adams", username="lilya"),
    User(name="Michael Brown", username="michaelb"),
    User(name="Natalie Reed", username="natalier"),
    User(name="Oliver Scott", username="olivers"),
    User(name="Penelope Moore", username="penelopem"),
    User(name="Quinn Allen", username="quinna"),
    User(name="Rachel Green", username="rachelg"),
    User(name="Samuel Hall", username="samuelh"),
    User(name="Tina Clark", username="tinacl"),
    User(name="Ulysses Grant", username="ulyssesg"),
    User(name="Victoria Hill", username="victoriah"),
    User(name="Walter White", username="walterw"),
    User(name="Xavier King", username="xavierk"),
    User(name="Yvonne Young", username="yvonne y"),
    User(name="Zoe Carter", username="zoec"),
    User(name="Aaron Patel", username="aaronp"),
    User(name="Bella Garcia", username="bellag"),
    User(name="Chris Evans", username="chrise"),
    User(name="David Lopez", username="davidl")
]